### ISSUE TITLE
Preparation of candidate hierarchical TADs using other TAD callers

### ISSUE THREAD

**Issue by QianzhaoJ** [lhqxinghun/TADfit#2]
Hi,
Thanks for developing so interesting tools for hierarchical TADs detection. I think it will be very helpful to explore the hierarchical relationship between TAD.
I find that the candidate hierarchical TAD are called by Topdom and using pseudo contact matrix. But if I have a set of existing TADs using other TAD callers, can I explore the hierarchical relationship between my existing TADs using TADfit?
Thanks in advance!

Best,
Zhao

**Comment by lhqxinghun** [comment]
Thank you for your interest in our software TADfit for identifying hierarchical TADs in replicate Hi-C data. The current version of TADfit does not support external input of TAD boundary points although it is a very good suggestion, and we may consider adding this function in a feature release.

**Comment by lhqxinghun** [comment]
@QianzhaoJ Thank you for your interest in our software TADfit for identifying hierarchical TADs in replicate Hi-C data. The current version of TADfit does not support external input of TAD boundary points although it is a very good suggestion, and we may consider adding this function in a feature release.
