### ISSUE TITLE
ERROR - No .txt file for Hi-C contact matrix found in the input directory

### ISSUE THREAD

**Issue by Shaedeycool** [lhqxinghun/TADfit#3]
Good afternoon,

Please could you assist I have hic matrices from HiC-Pro and I am struggling to understand how I can feed them to TADfit as input data. Or how can I process them to be able to use them in TADfit.

**Comment by lhqxinghun** [comment]
Thanks for your feedback. The reason for this error is as it is described, there is no Hi-C contact matrix in .txt format in the input folder. According to our tests, it can occur in the following cases:
(1) The path given is not correct, the input should be the path to the folder, not the file, please also look at our readme file and the example folder "./data/expdata/IMR90-chr21-25K"
(2)The path is correct, but the contact matrices under the folder are not in .txt format or their name do not end in .txt
Moreover, note that TADfit only supports dense input, meaning that the .txt file should contain m rows and m columns in it, not 3 columns or others.
